### ISSUE TITLE
DateTime was not properly set Book Entity

### ISSUE THREAD

**Issue by sujit13666** [sujit13666/Student2StudentApi#1]
**DateTime** is not properly set on the **Book Entity**

Following Code can be helpful:

**Form**

```
->add('lastUpdate','datetime',array(
                'widget' => 'single_text',
                'constraints' => array(
                    new DateTime(),
                    new NotBlank()
                )
            ));
```

**Controller**
```
$data['lastUpdate'] =  gmdate('Y-m-d H:i:s');
```
**BookORM**
```
lastUpdate:
            column: last_update
            type: datetime
            nullable: false
```
Fix that
